import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { CARS } from '../src/config.js';
import { Cars } from '../src/cars.js';
import { Traffic } from '../src/traffic.js';
const def = CARS.find(d => d.id === 'eb110'); assert(def);
const b = fs.readFileSync('docs/' + def.file), l = b.readUInt32LE(12), d = JSON.parse(b.subarray(20, 20 + l));
assert.equal(d.asset.extras.license.split(' ')[0], 'CC-BY-NC-4.0');
assert(!d.meshes.some(m => m.primitives.some(p => [1, 2, 21, 28, 45].includes(p.material))));
d.images = []; d.textures = []; d.materials = d.materials.map(m => ({ name: m.name }));
const j = Buffer.from(JSON.stringify(d)), jp = Buffer.alloc(Math.ceil(j.length / 4) * 4, 32); j.copy(jp);
const glb = Buffer.alloc(20 + jp.length + b.length - 20 - l); b.copy(glb, 0, 0, 12);
glb.writeUInt32LE(glb.length, 8); glb.writeUInt32LE(jp.length, 12); glb.writeUInt32LE(0x4e4f534a, 16);
jp.copy(glb, 20); b.copy(glb, 20 + jp.length, 20 + l);
const { scene } = await new GLTFLoader().parseAsync(glb.buffer, '');
const holder = new THREE.Group(); holder.add(scene); scene.rotation.y = Math.PI;
holder.updateMatrixWorld(true);
const box = new THREE.Box3().setFromObject(holder, true), size = box.getSize(new THREE.Vector3());
holder.scale.setScalar(def.length / size.z); holder.updateMatrixWorld(true); box.setFromObject(holder, true);
const center = box.getCenter(new THREE.Vector3()); holder.position.set(-center.x, -box.min.y, -center.z); holder.updateMatrixWorld(true);
box.setFromObject(holder, true); box.getSize(size);
assert(Math.abs(size.z - 4.4) < 1e-6); assert(size.x > 1.9 && size.x < 2.1); assert(size.y > 1 && size.y < 1.15); assert(Math.abs(box.min.y) < 1e-6);
const wheels = Cars.prototype._wheels(holder, def, { length: size.z, width: size.x, height: size.y });
assert.equal(wheels.length, 4);
assert.equal(wheels.filter(w => w.pivot.position.z < 0).length, 2);
assert.equal(wheels.filter(w => w.pivot.position.x < 0).length, 2);
for (const w of wheels) {
  assert(w.radius > .25 && w.radius < .37);
  const center = w.pivot.position.clone(); w.pivot.rotation.x = 2.3; holder.updateMatrixWorld(true);
  assert(w.pivot.position.equals(center));
}
const head = new THREE.Box3(), tail = new THREE.Box3();
holder.traverse(o => { if (o.isMesh && /Hlight/.test(o.material.name)) head.expandByObject(o, true); if (o.isMesh && o.material.name === 'TailLight') tail.expandByObject(o, true); });
assert(head.max.z < 0); assert(tail.min.z > 0);
for (const [b, point] of [[head, def.lamps.head], [tail, def.lamps.tail]]) assert(b.clone().expandByScalar(.06).containsPoint(new THREE.Vector3(...point)), 'Lamp outside actual bulb bounds');
console.log(`PASS EB110: ${size.toArray().map(v => v.toFixed(3)).join(' × ')} m, ground aligned, front -Z, 4 animated wheels, lamps inside model bulb bounds; source/license preserved.`);
const traffic = new Traffic(new THREE.Scene(), { softTex: null });
const npc = traffic._vehicle({ group: holder, dim: { length: size.z, width: size.x, height: size.y, lamps: def.lamps }, wheels });
assert.equal(npc.wheels.filter(w => w.front).length, 2);
assert.equal(npc.headlights.glows.length, 2); assert.equal(npc.tails.length, 2);
assert(npc.headlights.glows.every(g => g.position.z < 0));
console.log('PASS EB110 NPC: four wheels retained, two front steering pivots, shared front/rear light rig.');
// Background NPC loads must never overwrite the selected-car progress label.
const cancelled = new Error('texture-free progress probe'); let backgroundUpdates = 0;
const probe = { onProgress: () => backgroundUpdates++, loader: { loadAsync: async (file, progress) => { progress({loaded: 5, total: 10}); throw cancelled; } } };
await assert.rejects(Cars.prototype._load.call(probe, def), e => e === cancelled);
assert.equal(backgroundUpdates, 0);
let progress = null;
await assert.rejects(Cars.prototype._load.call(probe, def, f => progress = f), e => e === cancelled);
assert.equal(progress, .5);
const pending = [], seen = [];
const selector = { list: [def, CARS[0]], token: 0, cache: new Map(), tilt: new THREE.Group(), _placeLights() {}, onProgress: f => seen.push(f),
  _load: (d, onProgress) => new Promise(resolve => pending.push({d, onProgress, resolve})) };
const first = Cars.prototype.select.call(selector, 0), second = Cars.prototype.select.call(selector, 1);
pending[0].onProgress(.9); pending[1].onProgress(.4); assert.deepEqual(seen, [.4]);
for (const p of pending) p.resolve({group: new THREE.Group(), dim: {}});
assert.equal(await first, false); assert.equal(await second, true);
console.log('PASS loading: NPC progress isolated; stale player loads cannot change label or active car.');
